//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rating()
        {
            this.Flow = new HashSet<Flow>();
        }
    
        public int RatingID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TeacherSubjectID { get; set; }
        public Nullable<int> ScoreId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flow> Flow { get; set; }
        public virtual Score Score { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual TeacherSubject TeacherSubject { get; set; }
    }
}
