//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ttimetable
    {
        public int Id { get; set; }
        public int ClassroomID { get; set; }
        public long Datetime { get; set; }
        public int SubjectId { get; set; }
        public int TeacherId { get; set; }
        public string Room { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Users Users { get; set; }
    }
}
